apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 8079
      protocol: TCP
      nodePort: 30250
  selector:
    name: front-end
